### ISSUE TITLE
Upgrade openssl to 0.10. or replace it with rusttls

### ISSUE THREAD

**Issue by kariae** [mattnenterprise/rust-ftp#84]
I have an issue when building a project that use ftp `'Unable to detect OpenSSL version`

from [here](https://github.com/sfackler/rust-openssl/issues/987#issuecomment-419246104) you can see that we need to upgrade openssl, I saw that we had the same issue before so why we don't move to rusttls which is newer than OpenSSL, and doesn't provide any support for TLS 1.1 and older, or any known-insecure algorithms. As a consequence, it's a lot simpler than OpenSSL, and is built purely in Rust, so doesn't require any magic to cross-compile.

**Comment by LegitBaboulinet** [comment]
I am also facing this issue on Manjaro. Here's the backtrace :
`
[lucas@lucas-vm test-ftp]$ export RUST_BACKTRACE=1

[lucas@lucas-vm test-ftp]$ cargo build
   Compiling num-traits v0.2.6
   Compiling winapi-build v0.1.1
   Compiling semver-parser v0.7.0
   Compiling num-integer v0.1.39
   Compiling libc v0.2.51
   Compiling winapi v0.2.8
   Compiling cc v1.0.35
   Compiling num-iter v0.1.37
   Compiling pkg-config v0.3.14
   Compiling foreign-types-shared v0.1.1
   Compiling openssl v0.9.24
   Compiling bitflags v0.9.1
   Compiling lazy_static v1.3.0
   Compiling regex-syntax v0.3.9
   Compiling utf8-ranges v0.1.3
   Compiling lazy_static v0.1.16
   Compiling kernel32-sys v0.2.2
   Compiling semver v0.9.0
   Compiling foreign-types v0.3.2
   Compiling rustc_version v0.2.3
   Compiling thread-id v2.0.0
   Compiling memchr v0.1.11
   Compiling time v0.1.42
   Compiling thread_local v0.2.7
   Compiling aho-corasick v0.5.3
   Compiling openssl-sys v0.9.43
   Compiling regex v0.1.80
   Compiling num v0.1.42
   Compiling chrono v0.2.25
error: failed to run custom build command for `openssl v0.9.24`
process didn't exit successfully: `/home/lucas/IdeaProjects/test-ftp/target/debug/build/openssl-7ffbea3cdfc8134c/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /home/lucas/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::begin_panic
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:412
   6: build_script_build::main
             at ./build.rs:16
   7: std::rt::lang_start::{{closure}}
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/rt.rs:64
   8: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
   9: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  10: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  11: std::rt::lang_start
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/rt.rs:64
  12: main
  13: __libc_start_main
  14: _start

warning: build failed, waiting for other jobs to finish...
error: build failed

`

**Comment by LegitBaboulinet** [comment]
UPDATE: I just came back to this and realized someone updated the cargo.toml file to upgrade the openssl dependency (PR #86). Although it has not been merged yet...
